name: Build and Push Isaac Lab GUI

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - Dockerfile
      - .github/workflows/build-and-push.yml

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to NVIDIA NGC
        uses: docker/login-action@v4
        with:
          registry: nvcr.io
          username: "$oauthtoken"
          password: ${{ secrets.NGC_API_KEY }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/isaac-lab-gui:3.0.0-beta2
            ${{ secrets.DOCKERHUB_USERNAME }}/isaac-lab-gui:latest
          provenance: false
          sbom: false